### ISSUE TITLE
Unity Kinect Demo

### ISSUE THREAD

**Issue by lvbubi** [GMark1996/BAGgins#3]
Bálint

**Comment by bandrika** [comment]
Unity Kinect Demo commit #3
I uploaded  the basic packages to use unity with kinect. The packages can be found in the
"KinectForWindows_UnityPro_2.0.1410" folder. The "Kinect proba 2" is the folder containing the unity project with the already importad kinecet packages and a test scene

**Comment by bandrika** [comment]
Unity Kinect Demo  
new project to test moving objects with kinect
